#
# Docker file used in GitHub Actions run enumeration.
#

FROM python:3.8-slim
LABEL maintainer="laraf@met.no"

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    pip install "rdflib" \
                "lxml"

VOLUME /src
WORKDIR /src
