version: '3.4'

services:
  html:
    build: .
    volumes:
      - ./doc:/workdir
    command: asciidoctor -n mmd-specification.adoc

  pdf:
    build: .
    volumes:
      - ./doc:/workdir
    command: asciidoctor-pdf -a pdf-themesdir=./ -a pdf-theme=mmd -n mmd-specification.adoc



