[[temporal_extent]]
=== temporal_extent

[cols="2,8"]
|=======================================================================
|Element |/mmd/temporal_extent

|Attributes |None

|Required |Yes

|Repetition allowed |Yes. Repetition is used when there are gaps in the
dataset.

|Description a|Defines the temporal extent or coverage of the dataset.
The extent is defined used two sub elements:

* start_date: The start date and time, in iso8601 format, for data collection or model coverage.
* end_date: The end date and time, in iso8601 format, for data collection or model coverage.
* If the dataset is not complete, the end_date element can be left empty.

|Example XML: a|
----
<temporal_extent>
 <start_date>2012-01-01T12:00:00Z<start_date>
 <end_date>2012-02-01T13:00:00Z</end_date>
</temporal_extent>
----

|DIF equivalent |/DIF/Temporal_Coverage

|ISO equivalent |/gmd:MD_Metadata/
gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent

|MM2 equivalent a|
/metadata@name='datacollection_period_from'

and

/metadata@name='datacollection_period_to'

|=======================================================================
