[[keywords]]
=== keywords

[cols="2,8"]
|=======================================================================
|Element |/mmd/keywords

|Attributes a| 

* vocabulary: The vocabulary where the keyword is fetched from. The vocabulary “none” is used if the keyword is not from a vocabulary. The recommended vocabulary to use is "GCMD", see <<variable-parameter-descriptions>> for further details. Other valid vocabularies are e.g. "WIGOS". Search services are currently based on GCMD Science keywords.

|Required |Yes

|Repetition allowed a| Yes.

It is expected that different keyword elements have different vocabulary
child elements.

|Description a|
A set of keywords describing the dataset. The keywords should be fetched
from a pre-defined vocabulary, but this is not a requirement. This
element has two child elements:

* reference: URI to machine readable form of the vocabulary used.
* keyword: A single keyword describing the dataset. This can be hierarchically like GCMD using a separator.
* separator: the character used as separator. This could be e.g. the GCMD ‘>’, but in XML this is encoded as ‘&gt;’. Other valid separators are: \| / -. 
Valid controlled vocabularies are GCMD Science Keywords
link:#anchor-2[[10]], Climate and Forecast Standard Names
link:#anchor-3[[11]], SeaDataNet link:#anchor-4[[12]] etc. The primary
usage for this element is to describe variables in the dataset, but it
could also be used to describe other features.

|Example XML: a|
----
<keywords vocabulary=”MyOwnVocab”>
     <keyword>ice_edge</keyword>
     <keyword>Manual Generated Ice Edge</keyword>
</keywords>

<keywords vocabulary=”GCMD”>
    <separator>-</separator>
    <reference>https://wiki.earthdata.nasa.gov/display/CMR/GCMD+Keyword+Access</reference>
    <keyword>Earth Science - Climate Indicators - Teleconnections - North Atlantic Oscillation</keyword>
</keywords>
----

|DIF equivalent |/DIF/Parameters

|ISO equivalent |/gmd:MD_Metadata
/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword/gco:CharacterString

|MM2 equivalent |/metadata@name='variable'

|=======================================================================
