[[dataset_citation]]
== dataset_citation

[cols="2,8"]
|=======================================================================
|Element |/mmd/dataset_citation

|Attributes |None

|Required |No

|Repetition allowed |Yes

|Description a|
A description of how the dataset should be properly cited. If this
information is not available, a citation string will be generated from the
metadata available. This element has the following child elements:

* author: The name of the organization(s) or individual(s) with primary intellectual responsibility for the data set's development. This is a mandatory element and is a comma separated list.
* publication_date: The publication/reference date for the (cited) resource. 
* title: The title of the data set, this may be the same as Entry Title or the title of a report or paper.
* series: journal, report series or similar for documents.
* edition:  The version of a cited resource.
* volume: The order or sequence of a resource in a series or set.
* issue: The issue number of a resource (usually within a volume).
* publication_place: The name of the city (and state or province and country if needed) where the resource was made available.  This is required if this form is used.
* publisher: The name of the individual(s) or organization(s) that made the resource available.  This is required if this form is used.
* pages: The range of pages or total number of pages of a cited resource.
* isbn: International Standard Book Number (if available).
* doi: Digital Object Identifier (if available).
* url: The URL of the online resource containing the cited resource (not necessary if DOI is provided).
* other: Additional free-text reference information.

|Example XML: a|
----
<dataset_citation>
    <author>Cristian Lussana, Ole Einar Tveito, Andreas Dobler, and Ketil Tunheim</author>
    <title>seNorge_2018, daily precipitation, and temperature datasets over Norway</title>
    <series>Earth System Science Data</series>
    <volume>11</volume>
    <issue>4</issue>
    <edition></edition>
    <publication_date>2019-10-01</publication_date>
    <publisher>Copernicus Publications</publisher>
    <pages></pages>
    <isbn></isbn>
    <doi>https://doi.org/10.5194/essd-11-1531-2019</doi>
    <url></url>
    <other></other>
</dataset_citation>
----

|DIF equivalent |/DIF/Data_Set_Citation

|ISO equivalent a|
There are no direct equivalent in ISO for this element as a whole, but
parts can be put into citation information.

*dataset_release_date* can be translated to

/gmd:MD_Metadata
/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:DateTime

where gmd:CI_DateTypeCode has attribute codeListValue="publication"

*other_citation_details* can be translated to

gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:otherCitationDetails

|MM2 equivalent |NA

|=======================================================================
