[[keywords]]
=== keywords

[cols="2,8"]
|=======================================================================
|Element |/mmd/keywords

|Attributes a| 

[[keywords_vocabulary]]
* vocabulary: The vocabulary where the keyword is fetched from. The vocabulary “None” is used if the keyword is not from a vocabulary. The recommended vocabularies to use are listed in <<keywords-vocabulary>>, see also <<variable-parameter-descriptions>> for further details. Search services are currently based on GCMD Science keywords (GCMDSK).

|Required |Yes

|Repetition allowed a| Yes.

It is expected that different keyword elements have different vocabulary
child elements.

|Description a|
A set of keywords describing the dataset. The keywords should be fetched
from a pre-defined vocabulary, but this is not a requirement. This
element has two child elements:

* resource: URI to machine readable form of the vocabulary used.
* keyword: A single keyword describing the dataset. This can be hierarchically like GCMD using a separator.
* separator: the character used as separator. This could be e.g. the GCMD ‘>’, but in XML this is encoded as ‘&gt;’. Other valid separators are: \| / -.

//Additional controlled vocabularies may be used, as WIGOS (https://codes.wmo.int/wmdr/) and SeaDataNet <<anchor-4, (see 12)>> etc.
The primary usage for this element is to describe variables in the dataset, but it could also be used to describe other features.

|Example XML: a|
----

<keywords vocabulary="GCMDSK">
    <keyword>Earth Science &gt; Climate Indicators &gt; Teleconnections &gt; North Atlantic Oscillation</keyword>
    <resource>https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords</resource>
    <separator>&gt;</separator>
</keywords>
----

|DIF equivalent |/DIF/Parameters

|ISO equivalent |/gmd:MD_Metadata
/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword/gco:CharacterString
|=======================================================================
