[[data_access]]
== data_access

[cols="2,8"]
|=======================================================================
|Element |/mmd/data_access

|Attributes |None

|Required |No

|Repetition allowed |Yes

|Description a|Description of how to access the data in the dataset. This
element has the following child elements:

* type: Description of the type of data access. Data Access Types
* name: The name of the data access mechanism.
• description: A short description of the data access type and purpose (if necessary).
* resource: The URL used to access the data. E.g. for WMS this should point at the GetCapabilities document. 
* wms_layers: WMS servers behave very different. Some servers has huge GetCapabilities documents with several thousand entries. The purpose of this element is to predefine a number of WMS layers. The first WMS layer will be presented initially1 if the user requests visualisation.

|Example XML: a|
----
<data_access>
     <type>OGC WMS</type>
     <resource>http://...</resource>
     <description>...</description>
     <wms_layers>
     <wms_layer>sea_ice_concentration</layer>
     </wms_layers>
</data_access>
----

|DIF equivalent |/Related_UrlRL

|ISO equivalent |/gmd:MD_Metadata/
gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource

|MM2 equivalent a|
link:../../../../metadata@name[/metadata@name]='dataref'

link:../../../../metadata@name[/]link:../../../../metadata@name[metadata@name]='dataref_OPENDAP'

link:../../../../metadata@name[/]link:../../../../metadata@name[metadata@name]='dataref_WMS'

WMS layer information is currently available only through XMD documents.

|=======================================================================
