[[instrument]]
=== instrument

[cols="2,8"]
|=======================================================================
|Element |/mmd/instrument

|Attributes |None

|Required |No

|Repetition allowed |Yes

|Description a|
Instrument used to collect the data. The element is described using two
child elements:

* short_name: is the abbreviated name of the instrument used to acquire the data. 
* long_name: is the full name of the instrument used to acquire the data.
* mode: is the operating mode of the instrument (if applicable).
    * polarisation: polarisation mode when applicable.
* product_type: is the type of product generated (if applicable)

See <<instruments>>, <<instrument-modes>> and
<<polarisation-modes>> for list.

|Example XML: a|
----
<instrument>
    <short_name>MODIS</short_name>
    <long_name>Moderate Resolution Imaging Spectroradiometer</long_name>
<instrument>

or

<mmd:instrument>
    <mmd:short_name>SAR-C SAR</mmd:short_name>
    <mmd:long_name>Synthetic Aperture Radar (C-band)</mmd:long_name>
    <mmd:mode>IW
    <mmd:polarisation>VV VH</mmd:polarisation>
    </mmd:mode>
</mmd:instrument>
----

|DIF equivalent |/DIF/Instrument

|ISO equivalent a|
For ISO we just translate instruments to keywords belonging to a
specific vocabulary.

/gmd:MD_Metadata
/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword/gco:CharacterString
|=======================================================================
