[[related_information]]
=== related_information

[cols="2,8"]
|=======================================================================
|Element |/mmd/related_information

|Attributes |None

|Required |No

|Repetition allowed |Yes

|Description a|
Description of how to access the data in the dataset. This element has
the following child elements:

* type: Description of the type of information. A controlled vocabulary is required. See <<related-information-types>>.
* resource: The URL used. 
* description: Textual description on the resource.

This element should be used for e.g. THREDDS landing pages. i.e. that is the
pages providing the overview of services (HTTP, OPeNDAP, WMS, ...) for a
dataset. The specific web services for data access are to be added using <<data_access>>.

|Example XML: a|
----
<related_information>
    <type>Project home page</type>
    <resource>URI</resource>
</related_information>

<related_information>
    <type>Dataset landing page</type>
    <resource>URI</resource>
</related_information>
----

|DIF equivalent a|
/Related_Url

View Related Information

|ISO equivalent |/gmd:MD_Metadata/
gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource

|MM2 equivalent
|link:../../../../metadata@name[/metadata@name]='dataref'


|=======================================================================
