[[reference]]
=== reference (NOT USED)

[cols="2,8"]
|=======================================================================
|Element |/mmd/reference

|Attributes |Type. Attribute used to signal if the reference is specified as freetext or using fields. Authors note: This attribute is required for easier identification of different types references based using Xpath.:

|Required |No

|Repetition allowed |Yes

|Description a|
The reference element describes key bibliographic citations pertaining
to the data set.

Bibliographic citations may be populated as a block of text in the
free-text field or as text in subfields (see below). Citations in the
free-text field may be provided in styles used by professional
scientific journals such as the American Geophysical Union (AGU),
American Psychological Association (APA), or Modern Language Association
(MLA).

The field can contain the following sub elements:

* author: The name of the individual(s) or organization(s) with primary intellectual responsibility for the cited resource's development. This is required if this form is used.
* publication_date: The publication/reference date for the cited resource.  If the Publication Date is not known, please use "Unknown".  This is required if this form is used.
* title: The title (name) of the cited resource.  This is required if this form is used.
* Series: The name of a resource series, or aggregate (collection) resource of which the cited resource is a part.
* edition:  The version of a cited resource.
* volume: The order or sequence of a resource in a series or set.
* issue: The issue number of a resource (usually within a volume).
* report_number: The unique number or code assigned to a resource by the issuing organization(s).
* publication_place: The name of the city (and state or province and country if needed) where the resource was made available.  This is required if this form is used.
* publisher: The name of the individual(s) or organization(s) that made the resource available.  This is required if this form is used.
* pages: The range of pages or total number of pages of a cited resource.
* isbn: International Standard Book Number.
* doi: Digital Object Identifier.
* online_resource: The URL of the online resource containing the cited resource.
* other_reference_details: Additional free-text reference information.

|Example XML a|
----
<reference type=”fields”> +
<Author>Tillis, G. M.</Author> +
<Publication_Date>2001</Publication_Date> +
<Title>Measuring Taylor Slough boundary and internal flows, +
Everglades National Park, Florida</Title> +
<Series>USGS Open-File Report</Series> +
<Report_Number>01-225</Report_Number> +
<Publication_Place>Tallahassee, FL</Publication_Place> +
<Publisher>U.S. Geological Survey</Publisher> +

<online_resource>http://fl.water.usgs.gov/Abstracts/ofr01_225_tillis.html +
</Online_Resource> +
</reference>
----
|DIF equivalent |/Reference

|ISO equivalent |Not known if this maps to any element in ISO.
|=======================================================================
