[[data_center]]
=== data_center

[cols="2,8"]
|=======================================================================
|Element |/mmd/data_center

|Attributes |None

|Required |No

|Repetition allowed |No

|Description a|
Description about the datacenter responsible for the distribution of the
dataset. The element has the following child elements:

* data_center_name: The name of the data center. This field is split into two child elements:
  ** short_name: the short name or acronym of the data center.
  ** long_name: the long name (or full name) of the data center.
* data_center_url: URL to the data center's main website.

Information on the data centre contact person for a data centre is conveyed through the element <<personnel>>. See <<personnel>> for more information. The role of a data center contact must be “Data center contact”.

If an id is assigned to the dataset by the data center, it can be included as <<alternate_identifier>>.

|Example XML a|
----
<data_center>
     <data_center_name>
         <short_name>MET Norway</short_name>
         <long_name>Norwegian Meteorological Institute</long_name>
     </data_center_name>
     <data_center_url>http://met.no</data_center_url>
</data_center>
----

|DIF equivalent |/DIF/Data_Center

|ISO equivalent |/gmd:MD_Metadata
/gmd:distributionInfo/gmd:MD_Distribution/gmd:distributor/gmd:MD_Distributor/gmd:distributorContact/gmd:CI_ResponsibleParty
|=======================================================================
