[[storage_information]]
=== storage_information

[cols="2,8"]
|=======================================================================
|Element |/mmd/storage_information

|Attributes |

|Required |No

|Repetition allowed |No

|Description a|Information about the underlying data storage when this is
available. File format specifications must follow a controlled vocabulary,
as must checksums. Allowed file formats are available in https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/GranuleDataFormat/?format=rdf[skos].
Checksums can be md5sum, shasum (sha256sum, sha384sum,
sha512sum) and other higher order approaches. Sub elements include:

* file_name: File name for the file in question.
* file_location: Location of the file in the local file storage.
* file_format: Identification of the file format
* file_size: Size of file according to the units expressed as attribute
  unit. Valid units are MB, GB and TB.
* checksum: A checksum for the file. This element require attribute type
  to be present. 

Virtual datasets that are established through aggregation of individual
files on e.g. an OPeNDAP server are not described with this element. For
harvested data usually only file format is available, if any.

|Example XML: a|
----
<storage_information>
  <file_name>
    osisaf_radiative_flux_24h_hl_polstere-050_multi_202003051200.nc
  </file_name>
  <file_location>/home/steingod/Desktop</file_location>
  <file_format>NetCDF-CF</file_format>
  <file_size unit="GB">0.12</file_size>
  <checksum type="sha512sum">
ad33563f9ab3a6f2ba74ebd72cb1f45fda00d55121a29a29230147e3472ef267c50882b0e0b21ef9ee5ed5cc25e454167cd19a1818f1e13bc044b6fc3ef8f285
  </checksum>
</storage_information>
----

|DIF equivalent a|Not directly represented, but partly through Multimedia
Sample.

|ISO equivalent a|NA

|MM2 equivalent a|NA
|=======================================================================
