[[abstract]]
=== abstract

[cols=">20%,80%",adoc]
|=======================================================================
|Element |/mmd/abstract

|Attributes a| 

* xml:lang ISO language code for the language that the abstract is in

|Required |Yes

|Repetition allowed |Yes, but each repetition should have a different
language.

|Description a|
The abstract should summarize and described the dataset.

The following guidelines for a good abstract follows (from DIF):

* Capitalization should follow standard constructs. For readability, all capital letters or all lower case letters should not be used. Use the appropriate case where applicable.
* Acronyms should be expanded to provide understanding.
* Where applicable, the abstract should also include brief statements on the following information:
* Data processing information (gridded, binned, swath, raw, algorithms used, necessary ancillary data sets).
* Date available.
* Data set organization (description of how data are organized within and by file).
* Scientific methodology or analytical tools.
* Time gaps in data set coverage.
* Units and unit resolution.
* Similarities and differences of these data to other closely-related data sets.
* Other pertinent information.    
* Capitalization should follow standard constructs. For readability, all capital letters or all lower case letters should not be used. Use the appropriate case where applicable.
* Acronyms should be expanded to provide understanding.
* Where applicable, the abstract should also include brief statements on the following information:
* Data processing information (gridded, binned, swath, raw, algorithms used, necessary ancillary data sets).
* Date available.
* Data set organization (description of how data are organized within and by file).
* Scientific methodology or analytical tools.
* Time gaps in data set coverage.
* Units and unit resolution.
* Similarities and differences of these data to other closely-related data sets.
* Other pertinent information.

|Example XML: a|
----
<abstract xml:lang='en'>
The daily analysis of sea ice concentration are obtained from operation satellite images of the polar regions. It is based on atmospherically corretected signal and an optimal sea ice concentration algorithm. This product is available for free from the EUMETSAT Ocean and Sea Ice Satellite Application Facility (OSI SAF).  
</abstract>
----

|DIF equivalent |/Summary/Abstract

|ISO equivalent |/gmd:MD_Metadata/
gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract/gco:CharacterString

|MM2 equivalent |/metadata@name='abstract'
|=======================================================================
