[[related_information]]
=== related_information

[cols="2,8"]
|=======================================================================
|Element |/mmd/related_information

|Attributes |None

|Required |No

|Repetition allowed |Yes

|Description a|
Description of related information and how to access it. This element has
the following child elements:

[[related_information_types]]
* type: Description of the type of information. A controlled vocabulary is required. See <<related-information-types, Related Information Types>>.
* resource: The URL used. 
* description: Textual description on the resource.

This element should be used for e.g. THREDDS landing pages. i.e. that is the
pages providing the overview of services (HTTP, OPeNDAP, WMS, ...) for a
dataset. The specific web services for data access are to be added using <<data_access>>.
This element should also be used to provide links to related publications, e.g. data papers, scientific publications 
or relevant documentations. The resource should point to the landing page of the publications. 

|Example XML: a|
----
<related_information>
    <type>Project home page</type>
    <description>Project home page</description>
    <resource>URI</resource>
</related_information>

<related_information>
    <type>Dataset landing page</type>
    <description>Dataset landing page</description>
    <resource>URI</resource>
</related_information>

<related_information>
    <type>Scientific publication</type>
    <description>Author, Title (YYYY), Publisher, doi</description>
    <resource>URI</resource>
</related_information>

<related_information>
    <type>Other documentation</type>
    <description>Conference poster</description>
    <resource>URI</resource>
</related_information>

<related_information>
  <type>Observation facility</type>
  <description>WIGOS Station: KVITOYA (0-20000-0-01011)</description>
  <resource>https://oscar.wmo.int/surface/#/search/station/stationReportDetails/0-20000-0-01011</resource>
</related_information>

----

|DIF equivalent a|
/Related_Url

View Related Information

|ISO equivalent |/gmd:MD_Metadata/
gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource
|=======================================================================
