<?xml version="1.0" encoding="UTF-8"?>
<mmd xmlns="http://www.met.no/schema/mmd" xmlns:gml="http://www.opengis.net/gml"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/"
	xmlns:dc="http://purl.org/dc/elements/1.1/">

	<metadata_identifier>foo-bar-baz-1234</metadata_identifier>
	<alternate_identifier type="WIS">here-the-alternate-id</alternate_identifier>
	<title xml:lang="en">Foo Ice Charts for Sognsvann</title>
        <title xml:lang="no">Foo Is kart for Sognsvann</title>
	<abstract xml:lang="en">Foo is high resolution for...</abstract>
	<metadata_status>Active</metadata_status>
        <dataset_production_status>In Work</dataset_production_status>
	<collection>NMDC</collection>
	<last_metadata_update>
		<update>
			<datetime>2012-10-31T12:00:00Z</datetime>
			<type>Created</type>
			<note></note>
		</update>
		<update>
			<datetime>2020-03-31T10:23:00Z</datetime>
			<type>Major modification</type>
			<note>Changed structure of the metadata element.</note>
		</update>
	</last_metadata_update>
	<temporal_extent>
		<start_date>2012-01-01T12:00:00Z</start_date>
		<end_date>2012-02-01T13:00:00Z</end_date>
	</temporal_extent>
	<iso_topic_category>climatologyMeteorologyAtmosphere</iso_topic_category>
	<keywords vocabulary="MyOwnVocab">
		<keyword>ice_edge</keyword>
		<keyword>Manual Generated Ice Edge</keyword>
	</keywords>
	<keywords vocabulary="GCMD">
		<keyword>Earth Science - Climate Indicators - Teleconnections -North Atlantic Oscillation</keyword>
		<resource>https://gcmdservices.gsfc.nasa.gov/static/kms/</resource>
		<separator>-</separator>
	</keywords>


       <dataset_language>en</dataset_language>
       <operational_status>Pre-Operational</operational_status>
       <access_constraint>Open</access_constraint>
       <use_constraint>
	       <identifier>CC-BY-4.0</identifier>
	       <resource>http://spdx.org/licenses/CC-BY-4.0</resource>
       </use_constraint>

	<!-- several contacts -->
	<personnel>
		<role>Technical contact</role>
		<name>Ole Dole</name>
		<email>...</email>
		<phone>...</phone>
		<fax></fax>
		<organisation></organisation>
	</personnel>
	<personnel>
		<role>Metadata author</role>
		<name>Frode Dinessen</name>
		<email>istjenesten@met.no</email>
		<phone>77621300</phone>
		<organisation>Norwegian Meteorological Institute</organisation>
		<contact_address>
			<address>the address</address>
			<city>Oslo</city>
			<postal_code>0653</postal_code>
			<country>Norway</country>
		</contact_address>
	</personnel>


	<data_center>
		<data_center_name>
			<short_name>METNO</short_name>
			<long_name>Norwegian Meteorological Institute
			</long_name>
		</data_center_name>
		<data_center_url>http://met.no</data_center_url>
	</data_center>

	<!-- different access to data -->
	<data_access>
		<name>OGC WMS access to data</name>
		<type>OGC WMS</type>
		<resource>http://...</resource>
		<wms_layers>
			<wms_layer>sea_ice_concentration</wms_layer>
		</wms_layers>
	</data_access>
	<related_information>
		<type>Project home page</type>
		<description>The home page of the project</description>
		<resource>URI</resource>
	</related_information>
	<related_information>
		<type>Dataset landing page</type>
		<description>Landing page of the dataset containing additional information</description>
		<resource>URI</resource>
	</related_information>
	<project>
		<short_name>ICE</short_name>
		<long_name>Ice Coverage Everywhere</long_name>
	</project>

	<platform>
		<short_name>S1A</short_name>
		<long_name>Sentinel-1A</long_name>
		<resource>https://www.wmo-sat.info/oscar/satellites/view/396</resource>
		<orbit_relative>121</orbit_relative>
		<orbit_absolute>62391</orbit_absolute>
		<orbit_direction>ascending</orbit_direction>
		<instrument>
			<short_name>SAR-C</short_name>
			<long_name>Synthetic Aperture Radar (C-band)</long_name>
			<resource>https://www.wmo-sat.info/oscar/instruments/view/450</resource>
			<mode>IW</mode>
			<polarisation>VV+VH</polarisation>
		</instrument>
		<ancillary>
			<cloud_coverage>23.4</cloud_coverage>
			<scene_coverage>77</scene_coverage>
			<timeliness>NRT</timeliness>
		</ancillary>
	</platform>

	<activity_type>Space Borne Instrument</activity_type>

	<dataset_citation>
		<dataset_creator>OMI SIPS</dataset_creator>
		<dataset_editor>J. Smith, D. Johnson, M. Davis
		</dataset_editor>
		<dataset_title>OMI/Aura Level 1B VIS Global Geolocated Earth Shine
			Radiances 1-orbit L2 Swath 13x24 km
		</dataset_title>
		<dataset_series_name>OML1BRVG</dataset_series_name>
		<dataset_release_date>2009</dataset_release_date>
		<dataset_release_place>NASA Goddard Space Flight Center
		</dataset_release_place>
		<dataset_publisher>U.S. Geological Survey</dataset_publisher>
		<version>004</version>
		<data_presentation_form>Digital Science Data
		</data_presentation_form>
		<online_resource>http://disc.gsfc.nasa.gov/Aura/OMI/oml1brvg_v004.shtml
		</online_resource>
	</dataset_citation>


	<cloud_cover>
		<value unit="%">45</value>
	</cloud_cover>

	<geographic_extent>
		<rectangle srsName="EPSG:4326">
			<north>90</north>
			<south>-90</south>
			<east>180</east>
			<west>-180</west>
		</rectangle>
		<polygon>
			<gml:Polygon id="polygon" srsName="EPSG:4326">
				<gml:exterior>
					<gml:LinearRing>
						<gml:pos>
							-180 -90
						</gml:pos>
						<gml:pos>
							180 -90
						</gml:pos>
						<gml:pos>
							180 90
						</gml:pos>
						<gml:pos>
							-180 90
						</gml:pos>
						<gml:pos>
							-180 -90
						</gml:pos>
					</gml:LinearRing>
				</gml:exterior>
			</gml:Polygon>
		</polygon>
	</geographic_extent>
</mmd>
