<?xml version='1.0' encoding='ASCII'?>
<mmd:mmd xmlns:mmd="http://www.met.no/schema/mmd">
  <mmd:metadata_identifier>f0fd4810-fd63-528c-991a-c835ed635b89</mmd:metadata_identifier>
  <mmd:title xml:lang="en">SYNOP data from station SUNDSVALL HARNOSAND</mmd:title>
  <mmd:abstract xml:lang="en">Synoptic meteorological measurements from SUNDSVALL HARNOSAND
extracted from the WMO Global Telecommunication System (GTS).
Data are not quality controlled after extraction from GTS.</mmd:abstract>
  <mmd:metadata_status>Active</mmd:metadata_status>
  <mmd:dataset_production_status>In Work</mmd:dataset_production_status>
  <mmd:collection>ADC</mmd:collection>
  <mmd:collection>SIOS</mmd:collection>
  <mmd:collection>APPL</mmd:collection>
  <mmd:collection>YOPP</mmd:collection>
  <mmd:last_metadata_update>2018-02-27T16:00:00Z</mmd:last_metadata_update>
  <mmd:temporal_extent>
    <mmd:start_date>2013-01-01</mmd:start_date>
  </mmd:temporal_extent>
  <mmd:iso_topic_category>climatologyMeteorologyAtmosphere</mmd:iso_topic_category>
  <mmd:keywords vocabulary="none">
    <mmd:keyword>Atmospheric</mmd:keyword>
    <mmd:keyword>Clouds</mmd:keyword>
    <mmd:keyword>Humidity</mmd:keyword>
    <mmd:keyword>Observation</mmd:keyword>
    <mmd:keyword>Precipitation</mmd:keyword>
    <mmd:keyword>Pressure</mmd:keyword>
    <mmd:keyword>SYNOP</mmd:keyword>
    <mmd:keyword>Temperature</mmd:keyword>
    <mmd:keyword>Wind</mmd:keyword>
  </mmd:keywords>
  <mmd:keywords vocabulary="Climate and Forecast Standard Names">
    <mmd:keyword>air_pressure_at_sea_level</mmd:keyword>
    <mmd:keyword>thickness_of_snowfall_amount</mmd:keyword>
    <mmd:keyword>wind_speed_of_gust</mmd:keyword>
    <mmd:keyword>relative_humidity</mmd:keyword>
    <mmd:keyword>air_temperature</mmd:keyword>
    <mmd:keyword>sea_surface_temperature</mmd:keyword>
    <mmd:keyword>wind_speed</mmd:keyword>
    <mmd:keyword>wind_from_direction</mmd:keyword>
    <mmd:keyword>air_pressure</mmd:keyword>
    <mmd:keyword>precipitation_amount</mmd:keyword>
    <mmd:keyword>dew_point_temperature</mmd:keyword>
  </mmd:keywords>
  <mmd:keywords vocabulary="Global Change Master Directory">
    <mmd:keyword>Atmosphere &gt; Atmospheric Pressure &gt; Surface Pressure</mmd:keyword>
    <mmd:keyword>Atmosphere &gt; Atmospheric Temperature &gt; Surface Air Temperature</mmd:keyword>
    <mmd:keyword>Atmosphere &gt; Atmospheric Water Vapor &gt; Humidity</mmd:keyword>
    <mmd:keyword>Atmosphere &gt; Atmospheric Winds &gt; Surface Winds</mmd:keyword>
    <mmd:keyword>Atmosphere &gt; Clouds &gt; Cloud Amount/Frequency</mmd:keyword>
    <mmd:keyword>Atmosphere &gt; Clouds &gt; Cloud Types</mmd:keyword>
    <mmd:keyword>Atmosphere &gt; Precipitation &gt; Precipitation Amount</mmd:keyword>
    <mmd:keyword>Cryosphere &gt; Snow/Ice &gt; Snow Depth</mmd:keyword>
  </mmd:keywords>
  <mmd:dataset_language>en</mmd:dataset_language>
  <mmd:geographic_extent>
    <mmd:rectangle>
      <mmd:north>62.51667</mmd:north>
      <mmd:south>62.51667</mmd:south>
      <mmd:east>17.43333</mmd:east>
      <mmd:west>17.43333</mmd:west>
    </mmd:rectangle>
  </mmd:geographic_extent>
  <mmd:access_constraint>Free</mmd:access_constraint>
  <mmd:use_constraint>Free</mmd:use_constraint>
  <mmd:project>
    <mmd:short_name>YOPP</mmd:short_name>
    <mmd:long_name>WMO Year of Polar Prediction</mmd:long_name>
  </mmd:project>
  <mmd:project>
    <mmd:short_name>APPLICATE</mmd:short_name>
    <mmd:long_name/>
  </mmd:project>
  <mmd:project>
    <mmd:short_name>SIOS</mmd:short_name>
    <mmd:long_name>Svalbard Integrated Arctic Earth Observing System</mmd:long_name>
  </mmd:project>
  <mmd:activity_type>In Situ Land-based station</mmd:activity_type>
  <mmd:related_information>
    <mmd:type>Dataset landing page</mmd:type>
    <mmd:description/>
    <mmd:resource>https://thredds.met.no/thredds/obssynop.html?dataset=arcticdata/obsSynop02366</mmd:resource>
  </mmd:related_information>
  <mmd:personnel>
    <mmd:role>Investigator</mmd:role>
    <mmd:name>&#216;ystein God&#248;y</mmd:name>
    <mmd:organisation>Norwegian Meteorological Institute</mmd:organisation>
    <mmd:email>o.godoy@met.no</mmd:email>
    <mmd:phone/>
    <mmd:fax/>
  </mmd:personnel>
  <mmd:data_access>
    <mmd:type>OPeNDAP</mmd:type>
    <mmd:resource>https://thredds.met.no/thredds/dodsC/arcticdata/obsSynop/02366</mmd:resource>
  </mmd:data_access>
  <mmd:data_center>
    <mmd:data_center_name>
      <mmd:short_name>WMO</mmd:short_name>
      <mmd:long_name>World Meteorological Organisation</mmd:long_name>
    </mmd:data_center_name>
  </mmd:data_center>
</mmd:mmd>
